"""Add URL field to Audio with default values

Revision ID: badb52875ca2
Revises: 
Create Date: 2024-06-25 16:28:43.251479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'badb52875ca2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.String(length=255), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audio', schema=None) as batch_op:
        batch_op.drop_column('url')

    # ### end Alembic commands ###
