name: React CI

on:
  push:
    branches: [ "main" ]
    paths:
      - 'front/**'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'front/**'

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v4
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'npm'
        cache-dependency-path: 'front/package-lock.json'  # Spécifier le chemin complet du fichier package-lock.json si nécessaire

    - name: Install dependencies
      run: npm ci
      working-directory: 'front/'

    - name: Build
      run: npm run build --if-present
      working-directory: 'front/'
